[Service]
Environment="HTTP_PROXY="
Environment="HTTPS_PROXY="
Environment="http_proxy="
Environment="https_proxy="
Environment="NO_PROXY=fc00:f853:ccd:e793::/64,172.20.0.0/16,localhost,127.0.0.1,::1,10.96.0.0/16,10.244.0.0/16,cube-studio-control-plane,cube-studio-registry,.svc,.svc.cluster,.svc.cluster.local"
Environment="no_proxy=fc00:f853:ccd:e793::/64,172.20.0.0/16,localhost,127.0.0.1,::1,10.96.0.0/16,10.244.0.0/16,cube-studio-control-plane,cube-studio-registry,.svc,.svc.cluster,.svc.cluster.local"
