apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-config
  namespace: infra
data:
  dev-kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: cube-studio
        cluster:
          server: https://kubernetes.default.svc
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
      - name: cube-studio-service-account
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
      - name: cube-studio
        context:
          cluster: cube-studio
          user: cube-studio-service-account
          namespace: pipeline
    current-context: cube-studio
